### ISSUE TITLE
wizcfg is not behaving on cpm3

### ISSUE THREAD

**Issue by jayacotton** [durgadas311/cpnet-z80#1]
A>ifconfig
Shift Register SPI Wiznet v1.0
inet 192.168.0.172 netmask 255.255.255.0
dns server 192.168.0.1
ether 98.76.b6.11.00.c3

A>wizcfg
Node ID:  B2H
IP Addr:  178.178.178.178
Gateway:  178.178.178.178
Subnet:   178.178.178.178
MAC:      B2:B2:B2:B2:B2:B2
No Sockets Configured

**Comment by durgadas311** [comment]
I'll need some more information. What does "wizdbg g 0 0 64" show? Are you able to confirm that it works on CP/M 2.2?

I ran the Heathkit version of wizcfg and it is working on that platform, built from the same source. Different implementation of CP/M 3, though. There isn't anything in wizcfg that depends on CP/M 3, though.

**Comment by jayacotton** [comment]
It may be that Wayne found the bug.  I am looking at the way that z88dk sets up the stack, and there may be issues with how that gets done.

**Comment by jayacotton** [comment]
Well after moving ifconfig stack down a bunch, the bug is still there.
C>ping www.nasa.gov                                                             
Shift Register SPI Wiznet v1.0                                                  
PING WWW.NASA.GOV (99.84.230.93)                                                
 52 bytes from 99.84.230.93: icmp_seq=4321 time=80 ms                           
 52 bytes from 99.84.230.93: icmp_seq=4322 time=60 ms                           
 52 bytes from 99.84.230.93: icmp_seq=4323 time=60 ms                           
 52 bytes from 99.84.230.93: icmp_seq=4324 time=60 ms                           
 52 bytes from 99.84.230.93: icmp_seq=4325 time=60 ms                           
                                                                                
C>wizcfg                                                                        
Node ID:  B2H                                                                   
IP Addr:  178.178.178.178                                                       
Gateway:  178.178.178.178                                                       
Subnet:   178.178.178.178                                                       
MAC:      B2:B2:B2:B2:B2:B2                                                     
No Sockets Configured          

It does this even after a wizreset command.  If you are not seeing this, then
maybe its local to my machine.  Could be a build bug.  I will revert to the 
last copy I got from you, and test that.

**Comment by jayacotton** [comment]
yep.  Its a build problem.  I got your last and its working.

**Comment by jayacotton** [comment]
When I compare the binary files with diff it says they are different.
Lets inspect the source code to make certain its the correct version.

**Comment by durgadas311** [comment]
I noticed in previous email that you had built both the h8xspi and mt011 versions. Is it possible you accidentally used the Heathkit version on the RC2014?

**Comment by jayacotton** [comment]
This looks like a procedure problem.  The code is working now.

**Comment by durgadas311** [comment]
P.S. I did find a bug that might have caused this. Not sure why it disappeared by itself, though. The libwiznt.asm file had not been converted to the config scheme, so it was still compiling for the H8, not RC2014.
