### ISSUE TITLE
src/w5500c/makevars compile error

### ISSUE THREAD

**Issue by jrlodden** [durgadas311/cpnet-z80#14]
The makevars file has a compile error using "make HBA=z180csio NIC=w5500c"
The line below needs the '[oc,nr]' to allow compile 
WZCLINK = wizcfg,libwiznt'[oc,nr]'

Changes to:
WZCLINK = wizcfg,libwiznt

Thanks for the great work!

**Comment by durgadas311** [comment]
Thanks, John. That's been fixed in the repo now!
