### ISSUE TITLE
USB1232 has a build error

### ISSUE THREAD

**Issue by jayacotton** [durgadas311/cpnet-z80#17]
In the chrio.asm file at check0 there is code to program the pio port,  This is not needed since the boot loader
for cp/m programs the port.  So, fast fix is to comment out the ld a,xx and out instructions.  The bug is non fatal
but is untidy

**Comment by durgadas311** [comment]
Fixed. DRI does not allow underscores in labels/symbols.

**Comment by jayacotton** [comment]
o.k. thanks
