### ISSUE TITLE
WIZCFG: Add command to remove socket config

### ISSUE THREAD

**Issue by durgadas311** [durgadas311/cpnet-z80#20]
WIZCFG is missing any way to remove/erase/cancel a configured socket, so there is no way to free up a socket slot once it has been configured - short of invalidating the NVRAM block and re-configuring all settings.

Possible syntax:
1. `WIZCFG X {0..7,A:..P:,LST:}`
2. `WIZCFG {0..7} {X,sid ipadr port [keep]}`

Syntax 1 is an extension of the existing 'X' command that removes/erases CP/NET device mappings. Examples:
```
WIZCFG X A:
WIZCFG X LST:
WIZCFG X 0
```

Syntax 2 is an extension of the existing socket config command that replaces the config data with the special value 'X'. Examples:
```
WIZCFG 0 0 192.168.0.2 31100
WIZCFG 0 X
```

**Comment by jayacotton** [comment]
I could go with WIZCFG X 0 or WIZCFG 0 X  Both make sense to me.

**Comment by durgadas311** [comment]
The command "WIZCFG {0..7} X" will now delete a socket's config. This was added last year.
