### ISSUE TITLE
CP/Net on S100 machines....

### ISSUE THREAD

**Issue by jayacotton** [durgadas311/cpnet-z80#22]
There is a problem building CP/Net for a machine that lakes FRAM/NVRAM.  I my S100 machine I used a
third option DISK.   My interface library can be built for any option.

The CP/Net code does not seem to be happy with my solution.  It states that the NVRAM is not initialized.  Yep, its not.

I was able it cobble it together, but there are file errors, so I am hanging fire on what to do next.

My library is in inettools-z80/libinet.c  ( not the best name I know).  I abstract all the bits in there.

**Comment by durgadas311** [comment]
I'm not exactly sure what you're trying to accomplish or what issues you encountered. Using a local CP/M file as NVRAM should be possible, except for CP/NOS and network boot. CPNETLDR.COM and NDOS3.COM are capable of reading local files to setup the network prior to loading CP/NET, and WIZCFG should be able to write a file that contains the configuration data. But, CP/NET is using a separate section of "NVRAM" from inettools, so unless that section has been initialized with WIZCFG I don't think you'll be able to initialize automatically when starting CP/NET.

**Comment by jayacotton** [comment]
So I have tracked down a h/w problem on the S100 machine version of the wiznet board.   The bug is associated with the use
of inir instruction.  Not certain, but I think that during an inir op, the 'c' register is the i/o device address, but the 'b' register is
also presented to the bus.  In S100 land, that should not be a problem but is in my case.

My work around is to recode the data read loops with a direct inp spi$rd instruct etc.  This seems to get around the main issue
I was having.  

On my machine the file list back was ... well chaotic at best.   Still working out the details, but I'm thinking we can use a
conditional to build 2 versions of the snios.asm driver.  

WRT NVRAM, this is so useful a device that I am planning to add it to my S100 bus system, after VCF West I think.  
I did find that ndos3 will carry on without 'NVRAM', things are just a bit clunky.  BTW how would NDOS3.COM read a
configuration file ?

**Comment by durgadas311** [comment]
In order to be compatible with the Z80 CPU, *all* I/O decoding hardware *must* ignore A8-A15. Even the "8080 compatible" I/O instructions place register contents onto A8-A15, so that can never be assumed to be "00". Changing INIR/OUTIR is not sufficient to fix faulty I/O decoding.

**Comment by durgadas311** [comment]
NDOS3.COM is created by linking a "pre-processing" program with the NDOS3.RSX (actual CP/NET code that is relocated into high memory). For systems without NVRAM, the pre-processing is simply checking whether NDOS3 is already loaded/active. For NVRAM systems, additional code is added to read NVRAM and, possibly, initialize the network hardware (if NVRAM is valid). NVRAM content is always optional, even for CP/NET 1.2 CPNETLDR.COM, and never prevents loading of CP/NET - provided, of course, that the network hardware is usable without initialization.

"ndos3dup.asm" is the simple (default) pre-processing program that only checks for duplicate NDOS3. "ndos3wiz.asm" is the WizNET version that includes checking NVRAM and initializing - although the actual NVRAM/network-init code is in libraries shared with other programs. See the respective "makevars" files for compile/link dependencies for various versions. CPNETLDR has "cpnldr-w.asm" for the WizNET initialization from NVRAM (also linked with the same libraries).
