### ISSUE TITLE
Can't seem to run programs from network drives.

### ISSUE THREAD

**Issue by jayacotton** [durgadas311/cpnet-z80#4]
I started seeing this yesterday, when I started to use the locally built .com files.
I will do a git pull and rebuild and re-install.  

C>k:today                                                                       
K:TODAY?                                                                        

------------------

CP/NET 1.2 Status
=================
Requester ID = 03H
Network Status Byte = 10H
Disk device status:
  Drive A: = LOCAL
  Drive B: = LOCAL
  Drive C: = LOCAL
  Drive D: = LOCAL
  Drive E: = LOCAL
  Drive F: = LOCAL
  Drive G: = LOCAL
  Drive H: = LOCAL
  Drive I: = LOCAL
  Drive J: = LOCAL
  Drive K: = Drive C: on Network Server ID = 00H
  Drive L: = Drive D: on Network Server ID = 00H
  Drive M: = LOCAL
  Drive N: = LOCAL
  Drive O: = LOCAL
  Drive P: = LOCAL
Console Device = LOCAL
List Device = LOCAL

-----------------------

C>wizcfg
Node ID:  03H
IP Addr:  192.168.0.172
Gateway:  192.168.0.1
Subnet:   255.255.255.0
MAC:      98:76:B6:11:00:C4
Socket 0: 00H 192.168.0.120 31100 45

---------------------------------------

c:ifconfig
b:pip a:=c:ccp.spr
c:cpnetldr
c:wizcfg 0 0 192.168.0.120 31100 45
c:network k:=c:[0]
c:network l:=d:[0]

-------------------------------

java -jar CpnetSocketServer.jar conf=config
CpnetSocketServer v1.1
Using config in config
Server 00 Listening on 192.168.0.120 port 31100
Connection from 192.168.0.172 (31100)
Remote 192.168.0.172 is 03
Creating HostFileBdos 00 device with root dir /home/jay/HostFileBdos

**Comment by jayacotton** [comment]
I should have said that this is on CP/M 2.2

**Comment by jayacotton** [comment]
This seems to apply to the first drive mounted, on the second one I can run programs.

**Comment by durgadas311** [comment]
Are the files named in lower-case on the host?

**Comment by jayacotton** [comment]
That is the problem.  Had upper case file names.  Gotta learn.
