### ISSUE TITLE
Add cpsocket_debug to the server.

### ISSUE THREAD

**Issue by jayacotton** [durgadas311/cpnet-z80#7]
I find I need to see what the socket server is hearing from the client.  A debug start option would be very useful, like the one
on CpNetSerialServer

**Comment by durgadas311** [comment]
Had this code already done, just not installed. It is now in the 'contrib' version and doc is updated.

**Comment by jayacotton** [comment]
that was quick, thanks.

**Comment by jayacotton** [comment]
maybe I'm not saying it right, I'm not getting any logging.

cpnetserver_host = 192.168.0.120
cpnetserver_port = 31100
cpnetserver_temp = P
cpnetserver_sid = 00
cpnetserver_max = 16
cpnetserver_root_dir = /home/jay/HostFileBdos
cpnetserver_debug

**Comment by durgadas311** [comment]
Rats... chicken-egg issue. I believe I finally sorted it out. That explains why my testing was going badly, wasn't actually dumping messages at all. I've confirmed it is working now.

BTW, the commandline option "debug" would also enable it, and that was working before.
